services:
  sonobarr:
    image: ghcr.io/dodelidoo-labs/sonobarr:latest # pin to ghcr.io/dodelidoo-labs/sonobarr:0.7.0 for a specific release
    container_name: sonobarr
    env_file:
      - .env
    volumes:
      - ./config:/sonobarr/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:5000"
    restart: unless-stopped

# Need to attach Sonobarr to an external reverse-proxy network instead of
# publishing port 5000? Remove the `ports:` section above and add a `networks:`
# stanza that matches your proxy. See the README for details.
