services:
  sonobarr:
    build:
      context: .
      dockerfile: Dockerfile
    image: sonobarr-local
    container_name: sonobarr
    volumes:
      - ./config:/sonobarr/config
      - /etc/localtime:/etc/localtime:ro
      #- ./src:/sonobarr/src # only needed if you want to modify the source code
    #ports: # uncomment if you want to expose the app directly
      #- 5000:5000 # uncomment if you want to expose the app directly
    restart: unless-stopped
    environment:
      - last_fm_api_key=${last_fm_api_key}
      - last_fm_api_secret=${last_fm_api_secret}
      - lidarr_address=${lidarr_address}
      - quality_profile_id=${quality_profile_id}
      - lidarr_api_key=${lidarr_api_key}
      - youtube_api_key=${youtube_api_key}
    networks: # comment if you want to expose the app directly, in which case you will open ports
      npm_proxy: # comment if you want to expose the app directly, in which case you will open ports
        ipv4_address: 192.168.97.23 # Change to your desired and free IP. Comment if you want to expose the app directly, in which case you will open ports

networks:
    npm_proxy:
      external: true
