services:
  sonobarr:
    image: ghcr.io/dodelidoo-labs/sonobarr:latest # or ghcr.io/dodelidoo-labs/sonobarr:0.1.0 for a specific version
    container_name: sonobarr
    env_file:
      - .env
    volumes:
      - ./config:/sonobarr/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      npm_proxy:
        ipv4_address: 192.168.97.23 # change to an available IP on your proxy network

networks:
  npm_proxy:
    external: true
