services:
  sonobarr:
    build:
      context: .
      dockerfile: Dockerfile
    image: sonobarr-local
    container_name: sonobarr
    volumes:
      - ./config:/sonobarr/config
      - /etc/localtime:/etc/localtime:ro
      - ./src:/sonobarr/src # only needed if you want to modify the source code
    #ports: # unless you want to expose the app directly, otherwise use a reverse proxy
      #- 5000:5000
    restart: unless-stopped
    environment:
      - last_fm_api_key=${last_fm_api_key}
      - last_fm_api_secret=${last_fm_api_secret}
      - lidarr_address=${lidarr_address}
      - quality_profile_id=${quality_profile_id}
      - lidarr_api_key=${lidarr_api_key}
      - youtube_api_key=${youtube_api_key}
    networks: # unless you want to expose the app directly, in which case you will open ports
      npm_proxy:
        ipv4_address: 192.168.97.23

networks:
    npm_proxy:
      external: true
